development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: worship_development
  pool: 5
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: worship_test
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: worship_production
  pool: 5
  username: worship
  password: <REDACTED>
  host: localhost
